services:
  uyuni:
    image: docker.io/mbussolotto/uyuni-dev:latest
    network_mode: bridge
    command: sleep infinity
    depends_on:
      - db
  db:
    image: registry.opensuse.org/systemsmanagement/uyuni/master/docker/containers/uyuni-master-pgsql-4eclipse
    restart: unless-stopped
