version: '3.8'
services:
  uyuni:
    image: docker.io/mbussolotto/uyuni-dev:latest
    network_mode: service:db
    command: sh -c "mv /repository /workspaces/uyuni/java/buildconf/ivy/ &&
      mkdir -p /workspaces/uyuni/java/lib &&
      mv /uyuni-lib/* /workspaces/uyuni/java/lib/ &&
      tail -f /dev/null"
    depends_on:
      - db
  db:
    image: registry.opensuse.org/systemsmanagement/uyuni/master/docker/containers/uyuni-master-pgsql-4eclipse
    restart: unless-stopped
