apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-configmap
  namespace: "{{ .Release.Namespace }}"
data:
  config.yaml: |
    server: {{ .Values.server }}
    server_version: "{{ .Values.server_version }}"
    proxy_fqdn: {{ .Values.proxy_fqdn }}
    email: {{ .Values.email }}
    max_cache_size_mb: {{ .Values.max_cache_size_mb }}
    log_level: {{ .Values.log_level | default 1 }}
    ca_crt: |
{{ .Values.ca_crt | indent 6 }}
  squid_tuning: |
    # Add your Squid tuning configuration here
{{ .Values.squid_tuning | indent 4 }}
  apache_tuning: |
    # Add your Apache tuning configuration here
{{ .Values.apache_tuning | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: proxy-secret
  namespace: "{{ .Release.Namespace }}"
stringData:
  httpd.yaml: |
    httpd:
{{ .Values.httpd | toYaml | indent 6 }}
  ssh.yaml: |
    ssh:
{{ .Values.ssh | toYaml | indent 6 }}
