name: test-all-in-one-parallel-sets
on: pull_request
jobs:
  test-uyuni:
    uses: ./.github/workflows/test_all_in_one_common.yml
    strategy:
      fail-fast: false
      matrix:
        set: ['1', '2', '3', '4', '5']
    with:
      secondary_tests: "18_run_secondary_parallelizable_tests_subset.sh ${{ matrix.set }}"
